# This top-level key defines all the services (containers) you want to run.
services:
  # This is the name of your service (you can call it anything)
  splunk:
    # Tells Docker which image to download from Docker Hub
    image: splunk/splunk:latest
    # A custom name for your running container
    container_name: splunk_server
    hostname: splunkserver
    
    # Environment variables passed into the container
    environment:
      # Automatically accepts the license agreement on start
      - SPLUNK_START_ARGS=--accept-license
      # This is the required line to accept the general terms
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      # Sets the admin password. !!! CHANGE THIS !!!
      - SPLUNK_PASSWORD=YourSecurePasswordHere
      
    # Maps ports from your computer (host) to the container
    ports:
      # Maps host port 8000 to container port 8000 (for the Web UI)
      - "8000:8000"
      # Maps host port 9997 to container port 9997 (for data forwarding)
      - "9997:9997"
      
    # This connects the persistent volumes (defined below) to folders inside the container
    volumes:
      # Mounts the 'splunk_etc' volume to the container's config directory
      - splunk_etc:/opt/splunk/etc
      # Mounts the 'splunk_var' volume to the container's data/logs directory
      - splunk_var:/opt/splunk/var

# This top-level key defines the persistent storage volumes
# This ensures your data survives even if the container is removed.
volumes:
  splunk_etc:
  splunk_var: